export const pricingPlans = [
  {
    id: "starter",
    name: "Starter",
    price: "Starting at ₹14,999",
    description: "A beautiful first step into the digital world — elegant, heartfelt, and ready to impress.",
    cta: "Launch Your Event",
    ctaLink: "/contact",
    highlighted: false,
    dark: false,
    features: [
      { icon: "✦", text: "Beautifully crafted single-page experience" },
      { icon: "✦", text: "Flawless on every screen & device" },
      { icon: "✦", text: "Personalised contact & RSVP form" },
      { icon: "✦", text: "Optimised to be found on Google" },
      { icon: "✦", text: "One round of thoughtful refinements" },
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: "Starting at ₹29,999",
    description: "For moments that deserve more — a rich, immersive experience your guests will never forget.",
    cta: "Create Premium Experience",
    ctaLink: "/contact",
    highlighted: true,
    dark: false,
    features: [
      { icon: "✦", text: "Beautiful multi-chapter storytelling" },
      { icon: "✦", text: "Immersive luxury interactions & motion" },
      { icon: "✦", text: "WhatsApp & smart form integrations" },
      { icon: "✦", text: "Gallery, blog & portfolio showcase" },
      { icon: "✦", text: "Four rounds of loving revisions" },
    ],
  },
  {
    id: "signature",
    name: "Signature",
    price: "Starting at ₹54,999",
    description: "The ultimate bespoke digital experience — crafted with obsessive attention to every detail.",
    cta: "Book a Design Call",
    ctaLink: "/contact",
    highlighted: false,
    dark: true,
    features: [
      { icon: "✦", text: "Unlimited chapters, zero compromises" },
      { icon: "✦", text: "Cinematic performance & speed" },
      { icon: "✦", text: "Bespoke integrations & live content" },
      { icon: "✦", text: "Dynamic CMS — update anytime" },
      { icon: "✦", text: "White-glove priority support" },
    ],
  },
];
