export const services = [
  {
    id: "business",
    title: "Business Websites",
    outcome: "Turn visitors into paying customers",
    description:
      "A high-converting business website that builds instant credibility, showcases your work, and brings leads directly to your inbox — 24/7.",
    icon: "Briefcase",
    tags: ["Lead Generation", "SEO Ready", "Analytics", "WhatsApp CTA"],
    gradient: "from-[#0F172A] via-[#1e1040] to-[#2d1054]",
    accent: "from-[#FF4FCB] to-[#A855F7]",
    featured: true,
    viewLink: "/work",
  },
  {
    id: "wedding",
    title: "Wedding Websites",
    outcome: "Give your love story a home on the internet",
    description:
      "A stunning, story-first wedding website your guests will cherish — with RSVP, countdown, gallery, and every detail beautifully presented.",
    icon: "Heart",
    tags: ["RSVP", "Countdown", "Gallery", "Couple Story"],
    gradient: "from-[#fff0f8] to-[#f5eeff]",
    accent: "from-[#FF4FCB] to-[#f472b6]",
    featured: false,
    large: true,
    viewLink: "/work",
  },
  {
    id: "invitation",
    title: "Invitation Websites",
    outcome: "Send invites that actually get opened",
    description:
      "Personalised digital invitations for every occasion — elegant, shareable, and unforgettable.",
    icon: "MailCheck",
    tags: ["Digital Invite", "Venue Map", "RSVP"],
    gradient: "from-[#fdf4ff] to-[#ede9fe]",
    accent: "from-[#A855F7] to-[#6D28D9]",
    featured: false,
    viewLink: "/work",
  },
  {
    id: "reunion",
    title: "Reunion Websites",
    outcome: "Reunite everyone around one beautiful page",
    description:
      "A dedicated hub for batch reunions, family gatherings, and milestone celebrations with memories and registration.",
    icon: "Users",
    tags: ["Timeline", "Photo Gallery", "Registration"],
    gradient: "from-[#f0f9ff] to-[#ede9fe]",
    accent: "from-[#6D28D9] to-[#A855F7]",
    featured: false,
    viewLink: "/work",
  },
  {
    id: "housewarming",
    title: "Housewarming Websites",
    outcome: "Welcome your guests in style",
    description:
      "Elegant invite microsites for your new home celebrations with maps, schedules, and guest confirmations.",
    icon: "Home",
    tags: ["Location Map", "Guest RSVP", "Invite"],
    gradient: "from-[#fff7ed] to-[#fdf4ff]",
    accent: "from-[#f97316] to-[#FF4FCB]",
    featured: false,
    viewLink: "/work",
  },
  {
    id: "custom",
    title: "Something Unique?",
    outcome: "We craft anything you can imagine",
    description:
      "Portfolios, birthdays, memorials, launches — if it's a moment worth celebrating, we'll build the perfect digital experience for it.",
    icon: "Sparkles",
    tags: ["Custom Design", "Any Occasion", "Flexible"],
    gradient: "from-[#fdf4ff] to-[#fff0f8]",
    accent: "from-[#FF4FCB] to-[#6D28D9]",
    featured: false,
    viewLink: "/contact",
  },
];
